CREATE DATABASE mcpeshoop;
USE mcpeshoop;
CREATE TABLE products(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(50), description TEXT, price DECIMAL(5, 2), active INT DEFAULT 1, command VARCHAR(100), category INT, server INT, author INT);
CREATE TABLE servers(id INT PRIMARY KEY AUTO_INCREMENT, host VARCHAR(50), port VARCHAR(10), password VARCHAR(200));
CREATE TABLE categories(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(50), description TEXT);
CREATE TABLE users(id INT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(30), password TEXT);
INSERT INTO products(name, description, price, command, category, server, author) VALUES ('First Product', 'This is your first product.', 3.00, 'setgroup {player} rank', 1, 1, 1);
INSERT INTO servers(host, port, password) VALUES ('127.0.0.1', '19132', '$2y$12$N6FSH8yRo0YMQ4oPJHN1vOkv7GfK3OhVp22H/AjGoVLY.5Dm7ECYS');
INSERT INTO categories(name, description) VALUES ('First Category', 'This is your first category.');
INSERT INTO users(username, password) VALUES ('Todo56', '$2y$12$N6FSH8yRo0YMQ4oPJHN1vOkv7GfK3OhVp22H/AjGoVLY.5Dm7ECYS');